/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Tugas_Kelompok_1_PBO_2C;

import java.awt.Color;

/**
 *
 * @author ZUL
 */
public class Soft_Nim_UIN extends javax.swing.JFrame {

    /**
     * Creates new form Soft_Nim_UIN
     */
    public Soft_Nim_UIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Label_Jenjang = new javax.swing.JLabel();
        Label_Angkatan = new javax.swing.JLabel();
        Label_Fakultas = new javax.swing.JLabel();
        Label_Jurusan = new javax.swing.JLabel();
        Label_Jenis_Kelamin = new javax.swing.JLabel();
        Label_No_Mahasiswa = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Text_Input_NIM = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Warning_Nim = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Label_Hasil_Nama = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Text_Input_Nama = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Label_Hasil_Nama1 = new javax.swing.JLabel();
        Label_Hasil_Nama2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Software Melihat Info NIM");
        setBackground(new java.awt.Color(0, 153, 153));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Jenjang/ Program");

        jLabel2.setText("Angkatan              ");

        jLabel3.setText("Fakultas          ");

        jLabel4.setText("Jurusan");

        jLabel5.setText("Jenis Kelamin");

        jLabel6.setText("Nomor Mahasiswa");

        jLabel7.setText(":");

        jLabel8.setText(":");

        jLabel9.setText(":");

        jLabel10.setText(":");

        jLabel11.setText(":");

        jLabel12.setText(":");

        Label_Jenjang.setText("...............");

        Label_Angkatan.setText("...............");

        Label_Fakultas.setText("...............");

        Label_Jurusan.setText("...............");

        Label_Jenis_Kelamin.setText("...............");

        Label_No_Mahasiswa.setText("...............");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Jenjang)
                    .addComponent(Label_Angkatan)
                    .addComponent(Label_Fakultas)
                    .addComponent(Label_Jurusan)
                    .addComponent(Label_Jenis_Kelamin)
                    .addComponent(Label_No_Mahasiswa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(Label_Jenjang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(Label_Angkatan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(Label_Fakultas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(Label_Jurusan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(Label_Jenis_Kelamin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12)
                    .addComponent(Label_No_Mahasiswa))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(51, 255, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Text_Input_NIM.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel16.setText("Input NIM kamu 11 karakter disini :");

        Warning_Nim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Warning_Nim.setText("             ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel16)
                        .addGap(0, 133, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(Text_Input_NIM))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Warning_Nim, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Text_Input_NIM, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Warning_Nim)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 255, 0), null, null));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Software NIM UIN-SUSKA RIAU");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel14.setText("Source :  Kelompok 1 PBO 2C");

        Label_Hasil_Nama.setText("Keterangan NIM");

        jLabel17.setText("Ketikkan Nama Kamu disini");

        Text_Input_Nama.setText(" ");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Clear all");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Label_Hasil_Nama1.setText("                       ");

        Label_Hasil_Nama2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label_Hasil_Nama2.setText("                       ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Label_Hasil_Nama)))
                        .addGap(0, 42, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Text_Input_Nama))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_Hasil_Nama1)
                                    .addComponent(Label_Hasil_Nama2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_Input_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Label_Hasil_Nama1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_Hasil_Nama2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_Hasil_Nama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Label_Hasil_Nama1.setText("Terima Kasih");
        Label_Hasil_Nama2.setText("*"+Text_Input_Nama.getText()+" *");
        Label_Hasil_Nama.setText("__Dibawah ini info NIM kamu___ ");
        
        int z=Text_Input_NIM.getText().length();
        if (z==0){
            Warning_Nim.setText("Karakter tdk boleh kosong!!" );
            Warning_Nim.setForeground(Color.red);
        }
        else if (z<11) {
            Warning_Nim.setText("Karakter Kurang!!, info Nim akn salah");
            Warning_Nim.setForeground(Color.red);
        }
        else if (z>11) {
            Warning_Nim.setText("Karakter lebih!!, Info NIM akn salah");
            Warning_Nim.setForeground(Color.red);
            
        }
        else {
            Warning_Nim.setText("Jmlh Karakter NIM Anda Benar");
            Warning_Nim.setForeground(Color.blue);
        }
        
        //Menset Label Jenjang/Program Studi
        String a = Text_Input_NIM.getText();
        if (a.substring(0,1).equals("1")){
        Label_Jenjang.setText("S1");    
        }
        else if (a.substring(0,1).equals("2")){
        Label_Jenjang.setText("S2");    
        }
        else if (a.substring(0,1).equals("3")){
        Label_Jenjang.setText("S3");    
        }
        else if (a.substring(0,1).equals("0")){
        Label_Jenjang.setText("D3");    
        }
        else { Label_Jenjang.setText("Belum ada, Periksalah Karakter 1 Nim anda");
        }               
        //Menentukan Label Angkatan
        String b = Text_Input_NIM.getText();
        if (b.substring(1,3).equals("12")){
        Label_Angkatan.setText("20"+b.substring(1,3));
        }
        else if (b.substring(1,3).equals("11")){
        Label_Angkatan.setText("20"+b.substring(1,3));
        }
        else if (b.substring(1,3).equals("10")){
        Label_Angkatan.setText("20"+b.substring(1,3));
        }
        else if (b.substring(1,3).equals("09")){
        Label_Angkatan.setText("20"+b.substring(1,3));
        }
        else if (b.substring(1,3).equals("08")){
        Label_Angkatan.setText("20"+b.substring(1,3));
        }
        else if (b.substring(1,3).equals("07")){
        Label_Angkatan.setText("20"+b.substring(1,3));
        }
        else if (b.substring(1,3).equals("06")){
        Label_Angkatan.setText("20"+b.substring(1,3));
        }
        else if (b.substring(1,3).equals("05")){
        Label_Angkatan.setText("20"+b.substring(1,3));
        }
        else if (b.substring(1,3).equals("04")){
        Label_Angkatan.setText("20"+b.substring(1,3));
        }
        else if (b.substring(1,3).equals("03")){
        Label_Angkatan.setText("20"+b.substring(1,3));
        }
        else if (b.substring(1,3).equals("02")){
        Label_Angkatan.setText("20"+b.substring(1,3));
        }
        else if (b.substring(1,3).equals("01")){
        Label_Angkatan.setText("20"+b.substring(1,3));
        }
        else if (b.substring(1,3).equals("00")){
        Label_Angkatan.setText("20"+b.substring(1,3));
        }
        else { Label_Angkatan.setText("19"+b.substring(1,3));}
        
        
        //Menentukan Label Fakultas
        String c = Text_Input_NIM.getText();
        if (c.substring(3,4).equals("1")){
        Label_Fakultas.setText("Tarbiyah dan Keguruan");
        }
        else if (c.substring(3,4).equals("2")){
        Label_Fakultas.setText("Syariah dan Ilmu Hukum");
        }
        else if (c.substring(3,4).equals("3")){
        Label_Fakultas.setText("Ushuluddin");
        }
        else if (c.substring(3,4).equals("4")){
        Label_Fakultas.setText("Dakwah dan Ilmu Komunikasi");
        }
        else if (c.substring(3,4).equals("5")){
        Label_Fakultas.setText("Sains Dan Teknologi");
        }
        else if (c.substring(3,4).equals("6")){
        Label_Fakultas.setText("Psikologi");
        }
        else if (c.substring(3,4).equals("7")){
        Label_Fakultas.setText("Ekonomi dan Ilmu Sosial");
        }
        else if(c.substring(3,4).equals("8")){
        Label_Fakultas.setText("Pertanian dan Peternakan");
        }
        else { Label_Fakultas.setText("Unknown, /cek NIM kembali!!!");}
        
        
        //Jurusan di Fakultas Tarbiyah dan Keguruan
        String Tarbiyah = Text_Input_NIM.getText();
        if (Tarbiyah.substring(3,5).equals("11")){
        Label_Jurusan.setText("Pendidikan Agama Islam");
        }
        else if (Tarbiyah.substring(3,5).equals("12")){
        Label_Jurusan.setText("Pendidikan Bhs Arab");
        }
        else if (Tarbiyah.substring(3,5).equals("13")){
        Label_Jurusan.setText("Kependidikan Islam");
        }
        else if (Tarbiyah.substring(3,5).equals("14")){
        Label_Jurusan.setText("Pendidikan Bhs Inggris");
        }
        else if (Tarbiyah.substring(3,5).equals("15")){
        Label_Jurusan.setText("Pendidikan Matematika");
        }
        else if (Tarbiyah.substring(3,5).equals("16")){
        Label_Jurusan.setText("Pendidikan Ekonomi");
        }
        else if (Tarbiyah.substring(3,5).equals("17")){
        Label_Jurusan.setText("Pendidikan Kimia");
        }
        else if (Tarbiyah.substring(3,5).equals("18")){
        Label_Jurusan.setText("Pendidikan Guru Madarasah Ibtidaiyah");
        }
        else { Label_Jurusan.setText("Unknown, /cek NIM kembali!!!");        
        
        //Jurusan di Fakultas Syariah dan Ilmu Hukum
        String Syariah = Text_Input_NIM.getText();
        if (Syariah.substring(3,5).equals("21")){
        Label_Jurusan.setText("Ahwal al-Syakhsiah");
        }
        else if (Syariah.substring(3,5).equals("22")){
        Label_Jurusan.setText("Muamalah");
        }
        else if (Syariah.substring(3,5).equals("23")){
        Label_Jurusan.setText("Perbandiangan Hukum dan Madzhab");
        }
        else if (Syariah.substring(3,5).equals("24")){
        Label_Jurusan.setText("Jinayag Siyasah");
        }
        else if (Syariah.substring(3,5).equals("25")){
        Label_Jurusan.setText("Ekonomi Islam");
        }
        else if (Syariah.substring(3,5).equals("26")){
        Label_Jurusan.setText("Perbankan Syariah");
        }
        else if (Syariah.substring(3,5).equals("27")){
        Label_Jurusan.setText("Ilmu Hukum");
        }
                
        //Jurusan di Fakultas Ushuluddin
        String Ushulludin = Text_Input_NIM.getText();
        if (Ushulludin.substring(3,5).equals("31")){
        Label_Jurusan.setText("Aqidah Filsafat");
        }
        else if (Ushulludin.substring(3,5).equals("32")){
        Label_Jurusan.setText("Tafsir Hadits");
        }
        else if (Ushulludin.substring(3,5).equals("33")){
        Label_Jurusan.setText("Perbandingan Agama");
        }
        else { Label_Jurusan.setText("Unknown, /cek NIM kembali!!!");}
        
        
        //Jurusan di Fakultas Dakwah dan Ilmu Komunikasi
        String Dakwah = Text_Input_NIM.getText();
        if (Dakwah.substring(3,5).equals("41")){
        Label_Jurusan.setText("Pengembangan Masyarakat Islam");
        }
        else if (Dakwah.substring(3,5).equals("42")){
        Label_Jurusan.setText("Bimbingan Penyuluhan Islam");
        }
        else if (Dakwah.substring(3,5).equals("43")){
        Label_Jurusan.setText("Ilmu Komunikasi");
        }
        else if (Dakwah.substring(3,5).equals("44")){
        Label_Jurusan.setText("Manajemen Dakwah");
        }
        
        
               
        //Jurusan di Fakultas Sains dan Teknologi
        String SainsTek = Text_Input_NIM.getText();
        if (SainsTek.substring(3,5).equals("51")){
        Label_Jurusan.setText("Teknik Informatika");
        }
        else if (SainsTek.substring(3,5).equals("52")){
        Label_Jurusan.setText("Teknik Industri");
        }
        else if(SainsTek.substring(3,5).equals("53")){
        Label_Jurusan.setText("Sistem Informasi");
        }
        else if (SainsTek.substring(3,5).equals("54")){
        Label_Jurusan.setText("Matematika");
        }
        else if (SainsTek.substring(3,5).equals("55")){
        Label_Jurusan.setText("Teknik Elektro");
        }
               
        
        //Jurusan di Fakultas Psikologi
        String Psikologi = Text_Input_NIM.getText();
        if (Psikologi.substring(3,5).equals("61")){
        Label_Jurusan.setText("Psikologi");
        }
        
                
        //Jurusan di Fakultas Ekonomi
        String Ekonomi = Text_Input_NIM.getText();
        if (Ekonomi.substring(3,5).equals("71")){
        Label_Jurusan.setText("Manajemen");
        }
        else if (Ekonomi.substring(3,5).equals("72")){
        Label_Jurusan.setText("Manajemen Perusahaan");
        }
        else if (Ekonomi.substring(3,5).equals("73")){
        Label_Jurusan.setText("Akuntansi");
        }
        else if (Ekonomi.substring(3,5).equals("74")){
        Label_Jurusan.setText("Akuntansi D3");
        }
        else if (Ekonomi.substring(3,5).equals("75")){
        Label_Jurusan.setText("Administrasi Negara");
        }
        else if (Ekonomi.substring(3,5).equals("76")){
        Label_Jurusan.setText("Administrasi Perpajakan");
        }
      
       
        
        //Jurusan di Fakultas Pertanian dan Peternakan
        String Pertanian = Text_Input_NIM.getText();
        if (Pertanian.substring(3,5).equals("81")){
        Label_Jurusan.setText("Ilmu Peternakan");
        }
        else if (Pertanian.substring(3,5).equals("81")){
        Label_Jurusan.setText("Ilmu Pertanian (AgroTeknologi)");
        }}
        
               
        String e = Text_Input_NIM.getText();
        if (e.substring(5,6).equals("1")){
        Label_Jenis_Kelamin.setText("Laki-Laki");
        }
        else if (e.substring(5,6).equals("2")){
        Label_Jenis_Kelamin.setText("Perempuan");
        }
        else { Label_Jenis_Kelamin.setText("Unknown, /cek NIM kembali!!!");}
        
        
                        
        Label_No_Mahasiswa.setText(""+Text_Input_NIM.getText().substring(6));
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Text_Input_Nama.setText(null);
        Text_Input_NIM.setText(null);
        
        Label_Hasil_Nama1.setText(null);
        Label_Hasil_Nama2.setText(null);
        Label_Hasil_Nama.setText("Keterangan NIM");
        Label_Jenjang.setText(null);
        Label_Angkatan.setText(null);
        Label_Fakultas.setText(null);
        Label_Jurusan.setText(null);
        Label_Jenis_Kelamin.setText(null);
        Label_No_Mahasiswa.setText(null);
        Warning_Nim.setText(null);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Soft_Nim_UIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Soft_Nim_UIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Soft_Nim_UIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Soft_Nim_UIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Soft_Nim_UIN().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Angkatan;
    private javax.swing.JLabel Label_Fakultas;
    private javax.swing.JLabel Label_Hasil_Nama;
    private javax.swing.JLabel Label_Hasil_Nama1;
    private javax.swing.JLabel Label_Hasil_Nama2;
    private javax.swing.JLabel Label_Jenis_Kelamin;
    private javax.swing.JLabel Label_Jenjang;
    private javax.swing.JLabel Label_Jurusan;
    private javax.swing.JLabel Label_No_Mahasiswa;
    private javax.swing.JTextField Text_Input_NIM;
    private javax.swing.JTextField Text_Input_Nama;
    private javax.swing.JLabel Warning_Nim;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
